select * from strain where strainname like '%Animal Mintz%'
select * from strain where strainname like '%Animal Tsunami%'
select * from strain where strainname like '%Apples and Bananas%'
select * from strain where strainname like '%Banana OG%'
select * from strain where strainname like '%Banana Punch%'
select * from strain where strainname like '%Blue Zushi%'
select * from strain where strainname like '%Bubble Bath%'
select * from strain where strainname like '%Chem D%'
select * from strain where strainname like '%Choka-Cola%'
select * from strain where strainname like '%Daywrecker%'
select * from strain where strainname like '%Dulce De Uva%'
select * from strain where strainname like '%Eastside Moonwalker%'
select * from strain where strainname like '%Fat Albert%'
select * from strain where strainname like '%Garlic Drip%'
select * from strain where strainname like '%Hybrid%'
select * from strain where strainname like '%Ice Cream Cake%'
select * from strain where strainname like '%Indica%'
select * from strain where strainname like '%OG Kush%'
select * from strain where strainname like '%Petrol Station%'
select * from strain where strainname like '%Pomelo Punch%'
select * from strain where strainname like '%Rose Especial%'
select * from strain where strainname like '%Sativa%'
select * from strain where strainname like '%Soap%'
select * from strain where strainname like '%Strawguava%'
select * from strain where strainname like '%Super Silver Haze%'
select * from strain where strainname like '%Too Much Nerdz%'
