// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terprint.Web.Data;

#nullable disable

namespace Terprint.Web.Migrations
{
    [DbContext(typeof(TerprintWebContext))]
    [Migration("20240708164346_202407081242")]
    partial class _202407081242
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GrowerStates", b =>
                {
                    b.Property<int>("GrowersGrowerId")
                        .HasColumnType("int");

                    b.Property<int>("StatesId")
                        .HasColumnType("int");

                    b.HasKey("GrowersGrowerId", "StatesId");

                    b.HasIndex("StatesId");

                    b.ToTable("GrowerStates");
                });

            modelBuilder.Entity("Terprint.Web.Models.Batch", b =>
                {
                    b.Property<int?>("BatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("BatchId"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("GrowerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StrainID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BatchId");

                    b.HasIndex("GrowerID");

                    b.HasIndex("StrainID");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("Terprint.Web.Models.Grower", b =>
                {
                    b.Property<int>("GrowerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrowerId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GrowerId");

                    b.ToTable("Grower");
                });

            modelBuilder.Entity("Terprint.Web.Models.Matrixes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("Matrix")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("Terpene")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matrixes");
                });

            modelBuilder.Entity("Terprint.Web.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int?>("BatchID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("Growerid")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RatingCategoryID")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingId");

                    b.HasIndex("BatchID");

                    b.HasIndex("RatingCategoryID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Terprint.Web.Models.RatingCategory", b =>
                {
                    b.Property<int>("RatingCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingCategoryId"));

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RatingCategoryType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RatingCategoryId");

                    b.ToTable("RatingCategory");
                });

            modelBuilder.Entity("Terprint.Web.Models.States", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StateAbbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateCapital")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StateRegion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("Terprint.Web.Models.Strain", b =>
                {
                    b.Property<int>("StrainId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StrainId"));

                    b.Property<string>("StrainDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StrainId");

                    b.ToTable("Strain");
                });

            modelBuilder.Entity("Terprint.Web.Models.THCValue", b =>
                {
                    b.Property<int>("THCValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("THCValueId"));

                    b.Property<string>("Analyte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BatchID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Dilution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LOQ")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Percent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("THCValueId");

                    b.HasIndex("BatchID");

                    b.ToTable("THCValues");
                });

            modelBuilder.Entity("Terprint.Web.Models.TerpeneValue", b =>
                {
                    b.Property<int>("TerpeneValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerpeneValueId"));

                    b.Property<int?>("BatchID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Scale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerpeneName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("TerpeneValueId");

                    b.HasIndex("BatchID");

                    b.ToTable("TerpeneValues");
                });

            modelBuilder.Entity("GrowerStates", b =>
                {
                    b.HasOne("Terprint.Web.Models.Grower", null)
                        .WithMany()
                        .HasForeignKey("GrowersGrowerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terprint.Web.Models.States", null)
                        .WithMany()
                        .HasForeignKey("StatesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Terprint.Web.Models.Batch", b =>
                {
                    b.HasOne("Terprint.Web.Models.Grower", "Grower")
                        .WithMany("Batches")
                        .HasForeignKey("GrowerID");

                    b.HasOne("Terprint.Web.Models.Strain", null)
                        .WithMany("Batches")
                        .HasForeignKey("StrainID");

                    b.Navigation("Grower");
                });

            modelBuilder.Entity("Terprint.Web.Models.Rating", b =>
                {
                    b.HasOne("Terprint.Web.Models.Batch", null)
                        .WithMany("Ratings")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terprint.Web.Models.RatingCategory", null)
                        .WithMany("Ratings")
                        .HasForeignKey("RatingCategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Terprint.Web.Models.THCValue", b =>
                {
                    b.HasOne("Terprint.Web.Models.Batch", null)
                        .WithMany("THCValues")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Terprint.Web.Models.TerpeneValue", b =>
                {
                    b.HasOne("Terprint.Web.Models.Batch", null)
                        .WithMany("TerpeneValues")
                        .HasForeignKey("BatchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Terprint.Web.Models.Batch", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("THCValues");

                    b.Navigation("TerpeneValues");
                });

            modelBuilder.Entity("Terprint.Web.Models.Grower", b =>
                {
                    b.Navigation("Batches");
                });

            modelBuilder.Entity("Terprint.Web.Models.RatingCategory", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("Terprint.Web.Models.Strain", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
