"""
Quick setup script for Azure Data Lake
"""

def quick_setup():
    print("🚀 QUICK AZURE DATA LAKE SETUP")
    print("="*50)
    
    # Get storage account name
    storage_account = input("\n📝 Enter your Storage Account name: ").strip()
    if not storage_account:
        print("❌ Storage account name is required")
        return
    
    # Get container name
    container = input("📝 Enter your Container name: ").strip()
    if not container:
        print("❌ Container name is required")
        return
    
    # Choose auth method
    print("\n🔐 Choose authentication method:")
    print("1. Azure CLI (easiest - run 'az login' first)")
    print("2. Service Principal (for production)")
    
    auth_choice = input("Enter choice (1 or 2): ").strip()
    
    use_cli = auth_choice == "1"
    
    # Service principal details
    tenant_id = client_id = client_secret = ""
    if not use_cli:
        tenant_id = input("📝 Enter Tenant ID: ").strip()
        client_id = input("📝 Enter Client ID: ").strip()
        client_secret = input("📝 Enter Client Secret: ").strip()
        
        if not all([tenant_id, client_id, client_secret]):
            print("❌ All Service Principal fields are required")
            return
    
    # Create config file
    config_content = f'''"""
Azure Data Lake Configuration
Generated by quick_setup.py on {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

# Storage Account Information
AZURE_STORAGE_ACCOUNT_NAME = "{storage_account}"
AZURE_CONTAINER_NAME = "{container}"

# Authentication
USE_AZURE_CLI = {use_cli}
AZURE_TENANT_ID = "{tenant_id}"
AZURE_CLIENT_ID = "{client_id}"
AZURE_CLIENT_SECRET = "{client_secret}"

# File Organization
BASE_PATH = "dispensaries/muv"
INCLUDE_DATE_FOLDERS = True
'''
    
    try:
        with open("azure_config.py", "w") as f:
            f.write(config_content)
        print("\n✅ Configuration saved to azure_config.py")
        
        # Test the connection
        print("\n🔍 Testing connection...")
        import test_connection
        success = test_connection.test_connection()
        
        if success:
            print("\n🎉 Setup complete! Ready to use Azure Data Lake.")
        else:
            print("\n⚠️  Configuration saved but connection test failed.")
            print("   Check your credentials and try again.")
            
    except Exception as e:
        print(f"\n❌ Error saving configuration: {e}")

if __name__ == "__main__":
    from datetime import datetime
    quick_setup()