"""
Create Service Principal using Azure CLI
"""
import subprocess
import json
import sys

def run_cli_command(command):
    """Run Azure CLI command and return result"""
    try:
        result = subprocess.run(command, shell=True, capture_output=True, text=True)
        if result.returncode != 0:
            print(f"❌ Command failed: {command}")
            print(f"Error: {result.stderr}")
            return None
        return result.stdout.strip()
    except Exception as e:
        print(f"❌ Error running command: {e}")
        return None

def create_service_principal():
    print("🚀 CREATING SERVICE PRINCIPAL WITH AZURE CLI")
    print("="*60)
    
    # Check if Azure CLI is installed and user is logged in
    print("1️⃣  Checking Azure CLI...")
    version_output = run_cli_command("az --version")
    if not version_output:
        print("❌ Azure CLI not installed. Install from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli")
        return False
    
    account_output = run_cli_command("az account show")
    if not account_output:
        print("❌ Not logged in. Run: az login")
        return False
    
    account_info = json.loads(account_output)
    print(f"✅ Logged in as: {account_info.get('user', {}).get('name', 'Unknown')}")
    print(f"   Subscription: {account_info.get('name', 'Unknown')}")
    
    # Get subscription ID and tenant ID
    subscription_id = account_info.get('id')
    tenant_id = account_info.get('tenantId')
    
    print(f"\n2️⃣  Using subscription: {subscription_id}")
    print(f"   Tenant ID: {tenant_id}")
    
    # Create the service principal
    app_name = "Terprint-DataLake-ServicePrincipal"
    print(f"\n3️⃣  Creating service principal: {app_name}")
    
    create_command = f'az ad sp create-for-rbac --name "{app_name}" --role "Storage Blob Data Contributor" --scopes "/subscriptions/{subscription_id}" --sdk-auth'
    
    sp_output = run_cli_command(create_command)
    if not sp_output:
        return False
    
    try:
        sp_info = json.loads(sp_output)
        
        print("✅ Service Principal created successfully!")
        print("\n📋 CREDENTIALS (save these securely):")
        print(f"   Tenant ID: {sp_info.get('tenantId')}")
        print(f"   Client ID: {sp_info.get('clientId')}")
        print(f"   Client Secret: {sp_info.get('clientSecret')}")
        print(f"   Subscription ID: {sp_info.get('subscriptionId')}")
        
        # Save to config file
        save_to_config(sp_info)
        
        return True
        
    except json.JSONDecodeError as e:
        print(f"❌ Error parsing service principal output: {e}")
        return False

def save_to_config(sp_info):
    """Save credentials to config file"""
    config_content = f'''"""
Azure Data Lake Configuration
Auto-generated by create_sp_cli.py
Created on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

# Storage Account Information (UPDATE THESE)
AZURE_STORAGE_ACCOUNT_NAME = "your-storage-account-name"  # ⚠️  UPDATE THIS
AZURE_CONTAINER_NAME = "your-container-name"             # ⚠️  UPDATE THIS

# Service Principal Authentication
USE_AZURE_CLI = False
AZURE_TENANT_ID = "{sp_info.get('tenantId')}"
AZURE_CLIENT_ID = "{sp_info.get('clientId')}"
AZURE_CLIENT_SECRET = "{sp_info.get('clientSecret')}"

# File Organization
BASE_PATH = "dispensaries/muv"
INCLUDE_DATE_FOLDERS = True
'''
    
    try:
        with open("azure_config.py", "w") as f:
            f.write(config_content)
        
        print(f"\n💾 Configuration saved to azure_config.py")
        print("⚠️  Don't forget to update the storage account and container names!")
        
    except Exception as e:
        print(f"❌ Error saving config: {e}")

def assign_storage_permissions():
    """Assign permissions to storage account"""
    print("\n4️⃣  ASSIGN STORAGE ACCOUNT PERMISSIONS:")
    
    # Get storage accounts
    storage_output = run_cli_command("az storage account list --query '[].{Name:name, ResourceGroup:resourceGroup}' -o json")
    if not storage_output:
        print("❌ Could not list storage accounts")
        return
    
    try:
        storage_accounts = json.loads(storage_output)
        
        if not storage_accounts:
            print("❌ No storage accounts found")
            return
        
        print("📋 Available storage accounts:")
        for i, account in enumerate(storage_accounts):
            print(f"   {i+1}. {account['Name']} (Resource Group: {account['ResourceGroup']})")
        
        # Let user choose
        try:
            choice = int(input(f"\nSelect storage account (1-{len(storage_accounts)}): ")) - 1
            if 0 <= choice < len(storage_accounts):
                selected_account = storage_accounts[choice]
                
                print(f"\n🔐 Assigning permissions to: {selected_account['Name']}")
                
                # Get service principal object ID
                sp_list_command = 'az ad sp list --display-name "Terprint-DataLake-ServicePrincipal" --query "[0].id" -o tsv'
                sp_object_id = run_cli_command(sp_list_command)
                
                if sp_object_id:
                    # Assign role
                    role_command = f"""az role assignment create \
                        --assignee {sp_object_id} \
                        --role "Storage Blob Data Contributor" \
                        --scope "/subscriptions/{json.loads(run_cli_command('az account show'))['id']}/resourceGroups/{selected_account['ResourceGroup']}/providers/Microsoft.Storage/storageAccounts/{selected_account['Name']}" """
                    
                    if run_cli_command(role_command):
                        print("✅ Permissions assigned successfully!")
                        
                        # Update config with storage account name
                        update_config_with_storage(selected_account['Name'])
                    else:
                        print("❌ Failed to assign permissions")
                else:
                    print("❌ Could not find service principal")
            else:
                print("❌ Invalid selection")
        except ValueError:
            print("❌ Invalid input")
            
    except json.JSONDecodeError:
        print("❌ Error parsing storage account list")

def update_config_with_storage(storage_account_name):
    """Update config file with storage account name"""
    try:
        # Read current config
        with open("azure_config.py", "r") as f:
            content = f.read()
        
        # Replace placeholder
        content = content.replace(
            'AZURE_STORAGE_ACCOUNT_NAME = "your-storage-account-name"',
            f'AZURE_STORAGE_ACCOUNT_NAME = "{storage_account_name}"'
        )
        
        # Write back
        with open("azure_config.py", "w") as f:
            f.write(content)
        
        print(f"✅ Updated config with storage account: {storage_account_name}")
        
    except Exception as e:
        print(f"❌ Error updating config: {e}")

if __name__ == "__main__":
    from datetime import datetime
    
    success = create_service_principal()
    
    if success:
        assign_storage_permissions()
        
        print("\n🎉 SETUP COMPLETE!")
        print("\nNext steps:")
        print("1. Update AZURE_CONTAINER_NAME in azure_config.py")
        print("2. Run test_connection.py to verify setup")
        print("3. Keep your credentials secure!")
    else:
        print("\n❌ Setup failed. Check the errors above.")